#!/bin/bash
print_help() {
echo " 

Corrige los vectores de difusión asociados a la direccion (bvecs) en caso de que la adquisición tenga una rotación.
Esta basado en los archivos que se obtienen del formato PAR/REC de Philips Achieva TX 3T, pero en teoria la correción de vectores para cualquier formato requiere de los siguientes pasos:

	1.Obtener la matriz de rotación. 
	  Para los archivos PAR/REC es el archivo '.omat' que se obtienes tras usar PARconv_v1.12.sh
	  omat es un archivo de texto que representa una matriz de 4x4 

	2.Rotar los vectores. 
	  Multiplicación de los vectores bvecs por la matriz omat

	3.Invertir Y y Z de los bvecs. 
	  Multiplica por -1 la coordenada Y & Z de los bvecs.

	4.Multiplica por la transformación de eddy. 
	  Multiplica los vectores rotados e invertidos por la matriz de transformación para cada volumen DWI que se obtienes tras usar eddy FSL.
	  Hay una matriz asociada a cada volumen o sea a cada fila XYZ tiene una transformación asociada.

	5.Genera un nuevo mif
	  Usa los vectores corregidos para crear un archivo mif con herramientas de mrtrix



NOTA: bvec y bval deben estar en formato COLUMNA!!!



Example :
	`basename $0` DWI.nii.gz DWI.bvecs DWI.bvals corrected.eddy DWI_corrected.nii.gz
		DWI.omat		Archivo con la matriz de rotación
		DWI.bvecs		Son los bvecs del volumen DWI
		DWI.bvals		Son los bvals del volumen DWI
		corrected.eddy		parametros corregidos de eddy
		DWI_corrected.nii.gz 	El NIFTI corregido por eddy & topup
		Out_name		Archivo mif con bvecs corregidos

Raul RC
INB, Jul 2017
raulrcruces@inb.unam.mx

"
}

if [ $# -lt 6 ]
then
	echo -e "\e[0;31m\n[ERROR]...Falta algun argumento: \e[0m"
	echo -e "	Matriz omat: $1 \n	bvecs: $2 \n	bvals: $3 \n	Corrected.eddy: $4 \n	DWI_corregido: $5 \n	Nuevo nombre: $6"
	print_help
	exit 1
fi

c=`wc -l $2 | awk '{print $1}'`
if ((c == 3)); 
then
	echo -e "\e[0;31m\n[ERROR]...bvecs estan en formato FILA, cambiar a COLUMNAS \e[0m"
	exit 0 
fi

c=`wc -l $3 | awk '{print $1}'`
if ((c == 1)); 
then
	echo -e "\e[0;31m\n[ERROR]...bvals estan en formato FILA, cambiar a COLUMNA \e[0m"
	exit 0 
fi

############## parameters ############## 
# Setting: mrtrix3 update, docmd & time
source /home/inb/lconcha/fmrilab_software/tools/setup_mrtrix3_git.sh
aloita=$(date +%s.%N)

############## Variables ############## 
trans=$1
bvec=$2
bval=$3
eddyparam=$4
DWI_corr=$5
nom=$6
mif=${nom%%.*}.mif

if [ -f $mif ]; then 
	echo -e "\e[0;31m\n[ERROR]...Ya existe un archivo  llamado $mif \e[0m"; exit 123; 
fi

# Starting!
echo -e "\e[0;44m \n Correccion de vectores de DWI y creacion de mif \n\e[0m"; 
echo -e "Parametros:	\n	Matriz omat: $1 \n	bvecs: $2 \n	bvals: $3 \n	Corrected.eddy: $4 \n	DWI_corregido: $5 \n	Nuevo nombre: $6"

# Crea un directorio para archivos temporales, al final se borrara
tmp=/tmp/vectorCorr_$$
mkdir $tmp
echo ""
echo -e "\e[0;32m\n	[INFO]... Directorio con archivos temporales: \e[0m"
echo "	$tmp"

############### ... filas en blanco?? ##############
c=`grep -c "^\s*$" $bvec`
if ((c > 0)); 
then
	echo  -e "\e[0;32m\n	[INFO]... Borrando filas en blanco de bvals & bvecs \e[0m"
	sed -i '/^\s*$/d' $bvec
	sed -i '/^\s*$/d' $bval
fi



############### ... Rota los vectores ##############
echo  -e "\e[0;32m\n	[INFO]... Rotando los bvecs de acuerdo a la matriz de transformacion (Angulacion)\e[0m"
rot=angulados.bvec
xfmrot $trans $bvec ${tmp}/$rot
echo "	Listo"


############## ... Invierte los vectores Y & Z ##############
echo  -e "\e[0;32m\n	[INFO]... Corrigiendo los vectores Y & Z\e[0m"
# Este paso es especial para los datos obtenidos del Philips Achieva Tx 3.0T!!!
b_Mtx=angulados.b 		# b-matrix para mrtrix

	# bvec - multiplicando Z y Y por -1
	awk '{print $1,-$2,-$3}' ${tmp}/$rot > ${tmp}/inv_YZ.bvec

	# Creando nuevo archivo con los vectores corregidos para Mrtrix
	paste ${tmp}/inv_YZ.bvec $bval > ${tmp}/$b_Mtx
echo "	Listo"



############## ... Multiplica por la transformación de eddy ############## 
echo  -e "\e[0;32m\n	[INFO]... Rotando vectores por las transformaciones de edyy/topup\e[0m"
export bvec_Pos="${tmp}/$b_Mtx"
export eddy="`pwd`/$eddyparam"

# NOTA: Aqui tienes que poner la via completa de donde esta el script ejecutable, debo de pensar en una mejor manera de hacerlo despues
python /misc/ernst/rcruces/git_here/rrcOpen/rotateBvec.py
echo "	Listo"


############### ... Nuevo mif con los vectores corregidos ############## 
echo  -e "\e[0;32m\n	[INFO]... Creando archivo DWI.mif con vectores corregidos \e[0m"
grad=${nom%%.*}_corregidos.b
paste ${b_Mtx%%.*}_rotated.bvec $bval > $grad

# Crea el archivo mif 
mrconvert -grad $grad $DWI_corr $mif
echo "	Listo"



############## Duration ############## 
rm -Rv $tmp ${b_Mtx%%.*}_rotated.bvec

# Ending time
lopuu=$(date +%s.%N)
eri=$(echo "$lopuu - $aloita" | bc)
echo -e "\033[38;5;220m TOTAL running time: ${eri} seconds \n\033[0m"


